# Generated by Django 3.2 on 2021-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='prefers',
            field=models.CharField(choices=[('tea', 'Prefers tea'), ('coffee', 'Prefers coffee')], default='tea', max_length=32),
        ),
    ]
